language: node_js

node_js:
  - 14.15.1

services:
  - postgresql
  - redis-server

before_script:
  - psql -c "create database ssm_test;" -U postgres

install:
  - yarn

script:
  - yarn test
 
notification:
  - email: false

after_success:
  - yarn run coverage
