language: node_js

node_js:
  - 13

services:
  - postgresql

before_script:
  - psql -c "create database ssm_test;" -U postgres

install:
  - yarn

script:
  - yarn test
 
notification:
  - email: false

after_success:
  - yarn run coverage
