name: ESLint

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"
      - name: Setup ESLint
        run: |
          yarn
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/nezago/nezago-guidelines/development/nezago-default-configs/javascript/.eslintrc.json
      - name: ESLint Report
        run: npx eslint .